language:
  node_js

cache:
  yarn: true

node_js:
  - "8.9.1"

sudo: required

addons:
  chrome: stable

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=google-chrome

install:
  - npm i -g nrm
  - nrm ls
  - nrm use npm
  - yarn
  - yarn global add codecov

script:
  - yarn run unit
  - codecov
