language:
  node_js

cache:
  yarn: true

node_js:
  - "8.9.1"

sudo: required

addons:
  chrome: stable

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=chrome-browser

install:
  - yarn
  - yarn global add codecov istanbul

script:
  - yarn run unit
  - codecov